version: '3.8'
services:
  bot:
    build: .
    volumes:
      - .:/app
    env_file:
      - ./conf/tokens.env
    depends_on:
      - db
    networks:
      - backend
  db:
    image: postgres:latest
    env_file:
      - ./conf/tokens.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: